# behat.yml
default:
    autoload:
        - %paths.base%/../
    formatters:
        pretty: true
    suites:
        core:
            filters:
              tags: "@coretest"
            paths:
                - %paths.base%/../Features
            contexts:
                - myTests\Contexts\BaseContext
                - myTests\Contexts\GoogleContext